use friendDB;
drop table tbl_friend;
create table tbl_friend (
	FRIEND_ID	BIGINT	NOT NULL	PRIMARY KEY,
	FRIEND_NAME	VARCHAR(5)	NOT NULL,	
	FRIEND_TEL	VARCHAR(13),		
	FRIEND_HP	VARCHAR(13)	NOT NULL,	
	FRIEND_ADDR	VARCHAR(100),		
	FRIEND_HOBBY	VARCHAR(20),		
	FRIEND_RELATION	VARCHAR(10)	NOT NULL	
);

